# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "www-data", :mount_options => ["dmode=775", "fmode=775"]

  config.vm.box = "precise32"

  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :forwarded_port, guest: 80, host: 8082
  
  config.vm.provision :shell, :path => File.symlink?(__FILE__) ? File.dirname(File.readlink(__FILE__)) + "/bootstrap.sh" : "/bootstrap.sh"

end
