#!/usr/bin/env bash

git clone git@github.com:agallou/openphoto-search.git
cd openphoto-search
curl -sS https://getcomposer.org/installer | php
php composer.phar install
Vagrantfiles init openphoto-search
vagrant up

